factorio:
  image: gameservers/factorio:latest
  environment:
    MODS_PATH: /opt/factorio/mods
    FACTORIO_BUILD: experimental
  ports:
    - 34197:34197/udp
  net: bridge
  volumes_from:
    - factorio-data
  labels:
    io.rancher.sidekicks: factorio-data
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

factorio-data:
  image: gameservers/factorio:latest
  net: none
  volumes:
    - /opt/factorio/saves
  command: /bin/true
  labels:
    io.rancher.container.start_once: "true"
